stages:
  - review
  - build
  - test
  - deploy

code_review_sonaqube:
  stage: review
  image: docker:19.03.14
  script:
    - echo "Code review with a tool like sonaqube"


build_internal_registry:
  stage: build
  image: docker:19.03.14
  script:
    - echo "Building the image"
    - apk add --no-cache gettext
    - export  NODE_ENV=${NODE_ENV} GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
    - rm .env
    - envsubst < .env.tmpl > .env
    - docker build -t registry.miaou.net/miaou/mousetrap .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD registry.miaou.net
    - docker tag registry.miaou.net/miaou/mousetrap registry.miaou.net/miaou/mousetrap:$CI_COMMIT_REF_NAME
    - docker push registry.miaou.net/miaou/mousetrap:$CI_COMMIT_REF_NAME
  environment:
    name: registry
    url: https://dashboard.registry.miaou.net


automated_test:
  stage: test
  image: docker:19.03.14
  script:
    - echo "automated test of the code"

deploy_stage:
  stage: deploy
  image: kubectl_deployer:v1.18.3
  script:
    - echo "Deploy to kubernetes"
    - envsubst < deploy/deployment.yaml > deploy/new-deployment.yaml
    - rm deploy/deployment.yaml
    - mv deploy/new-deployment.yaml deploy/deployment.yaml
    - envsubst < deploy/service.yaml > deploy/new-service.yaml
    - rm deploy/service.yaml
    - mv deploy/new-service.yaml deploy/service.yaml
    - envsubst < deploy/ingress.yaml > deploy/new-ingress.yaml
    - rm deploy/ingress.yaml
    - mv deploy/new-ingress.yaml deploy/ingress.yaml
    - kubectl config set-cluster kubernetes --server="$K8S_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials kubernetes-admin --token="$K8S_TOKEN"
    - kubectl config set-context default-context --cluster=kubernetes --user=kubernetes-admin
    - kubectl config use-context default-context
    - /bin/sh ./deploy/deploy-canal2-prod.sh

  except:
  - production
  - stagging